// routing : "/"
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'PalmSpring',
  description: 'Generated by create next app',
};

export default function Home() {
  return <div>메인입니다</div>;
}
