# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@v1.0.0
        with:
          password: ${{ secrets.INSTANCE_PWD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd palmspring-client/PalmSpringClient
            git fetch --all
            git reset --hard origin/develop
            yarn
            pm2 stop 0
            yarn build
            pm2 start yarn -- start
