name: deploy

on:
  push:
    branches: [main, develop]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'subdomain')
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Push New ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 039174979026.dkr.ecr.ap-northeast-2.amazonaws.com
          docker build --platform linux/amd64 -t palmspring-client .
          docker tag palmspring-client:latest 039174979026.dkr.ecr.ap-northeast-2.amazonaws.com/palmspring-client:latest
          docker push 039174979026.dkr.ecr.ap-northeast-2.amazonaws.com/palmspring-client:latest

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: palmspring
          environment_name: Palmspring-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: docker-compose.yaml
